// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FetuerismTask.Models
{
    public partial class Categories
    {
        [Key]
        [Column("CategoryID")]
        public int CategoryId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string CategoryName { get; set; }
    }
}